### ISSUE TITLE
API to pull in random fact of same theme chosen for matching images

### ISSUE THREAD

**Issue by jengle-dev** [juliaguas17/hardcore-memory-game#10]

**Comment by juliaguas17** [comment]
https://rapidapi.com/orthosie/api/trivia5/

**Comment by jengle-dev** [comment]
https://api.api-ninjas.com/v1/animals?name=


const axios = require("axios");

const options = {
  method: 'GET',
  url: 'https://animals-by-api-ninjas.p.rapidapi.com/v1/animals',
  params: {name: 'cheetah'},
  headers: {
    'X-RapidAPI-Key': '9669d39c2emsh061a8c7293d8ce8p1fb057jsn0823798c42bf',
    'X-RapidAPI-Host': 'animals-by-api-ninjas.p.rapidapi.com'
  }
};

axios.request(options).then(function (response) {
	console.log(response.data);
}).catch(function (error) {
	console.error(error);
});

**Comment by jengle-dev** [comment]
https://api-ninjas.com/api/animals

**Comment by jengle-dev** [comment]
trivia.js created and we're getting the response back from the api

**Comment by jengle-dev** [comment]
trivia created and then concatenated for fact in modal
